name: dev

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  ci:
    # The type of runner that the job will run on
    name: Test ${{ github.ref }} on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['16']
        os: [ubuntu-latest]

    steps:
      - name: Setup node.js environment
        uses: actions/setup-node@v3
        with:
          # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0
          node-version: ${{ matrix.node_version }}

      - name: Setup docker
        uses: docker-practice/actions-setup-docker@master
        run: |
          set -x
          docker version
          docker run --rm hello-world

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install npm modules, run tests, build app
        run: |
          npm ci
          npm run lint
          npm test
        env:
          APP_ENV: dev
          API_ENV: local
          NEXT_PUBLIC_REACH_CONNECTOR_MODE: ALGO
          NEXT_PUBLIC_REACH_CONSENSUS_NETWORK_PROVIDER: TestNet